name: Update Chroma Styles

on:
  schedule:
    - cron: "0 0 * * *" # Run daily at midnight
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.19"
      - name: Update Chroma
        run: |
          go get github.com/alecthomas/chroma@master
          go mod tidy
          go mod vendor
      - name: Build selfupdate
        run: go build -o selfupdate cmd/selfupdate/main.go
      - name: Run selfupdate
        run: ./selfupdate
      - name: Build gendoc
        run: |
          cd cmd/gendoc
          go build -mod=vendor
      - name: Run gendoc
        run: |
          cd cmd/gendoc
          ./gendoc
      - name: Commit and push changes
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add docs || true
          git add go.* vendor || true
          git commit -m "Update Chroma styles"
          git push
